"""modify sql to mysql

Revision ID: 8fedcabba5bd
Revises: 6b9e26a2492e
Create Date: 2023-08-24 20:58:25.605577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fedcabba5bd'
down_revision: Union[str, None] = '6b9e26a2492e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
