"""empty message

Revision ID: 2938a66475d6
Revises: 09092c3916e5
Create Date: 2023-08-21 05:41:21.386594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2938a66475d6'
down_revision: Union[str, None] = '09092c3916e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actions', 'damage_class',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actions', 'damage_class',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
