"""empty message

Revision ID: 3160890c512f
Revises: 
Create Date: 2023-08-21 04:44:06.954724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3160890c512f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('disaster', sa.String(length=20), nullable=False),
    sa.Column('damage_class', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('disaster')
    )
    op.create_index(op.f('ix_actions_disaster'), 'actions', ['disaster'], unique=False)
    op.create_table('regions',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('region_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('region_id')
    )
    op.create_index(op.f('ix_regions_region_id'), 'regions', ['region_id'], unique=False)
    op.create_table('classifier',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('disaster', sa.String(length=20), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_index(op.f('ix_classifier_class_id'), 'classifier', ['class_id'], unique=False)
    op.create_table('damage',
    sa.Column('d_id', sa.Integer(), nullable=False),
    sa.Column('disaster', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('d_value', sa.Integer(), nullable=True),
    sa.Column('d_human', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('damage_class', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ),
    sa.PrimaryKeyConstraint('d_id')
    )
    op.create_index(op.f('ix_damage_d_id'), 'damage', ['d_id'], unique=False)
    op.create_table('weather',
    sa.Column('w_id', sa.Integer(), nullable=False),
    sa.Column('disaster', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ),
    sa.PrimaryKeyConstraint('w_id')
    )
    op.create_index(op.f('ix_weather_w_id'), 'weather', ['w_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_w_id'), table_name='weather')
    op.drop_table('weather')
    op.drop_index(op.f('ix_damage_d_id'), table_name='damage')
    op.drop_table('damage')
    op.drop_index(op.f('ix_classifier_class_id'), table_name='classifier')
    op.drop_table('classifier')
    op.drop_index(op.f('ix_regions_region_id'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_actions_disaster'), table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###
